export type TTableKey =
  // 客户线索
  | "CUSTOMER_LEAD"
  // 客户指派
  | "CUSTOMER_ASSIGN"
  // 今日跟进
  | "FOLLOW_UP_TODAY"
  // 我的客户
  | "MY_CUSTOMER"
  // 机构管理
  | "INSTITUTIONAL_MANAGEMENT"
  // 员工机构绑定
  | "EMPLOYEE_INSTITUTION_BINDING"
  // 班次管理
  | "SHIFT_MANAGEMENT"
  // 渠道分组
  | "CHANNEL_GROUPING"
  // 渠道管理
  | "CHANNEL_MANGEMENT"
  // 员工渠道绑定
  | "EMPLOYEE_BIND"
  // 主播管理
  | "ANCHOR_MANAGE"
  // 平台管理
  | "PLATFORM_MANAGE"
  // 医美项目管理
  | "MAIN_DATA_PROJECT_MANAGE"
  // 角色配置
  | "BASIC_ROLE"
  // 员工管理
  | "BASIC_EMPLOYEE"
  // 字典配置
  | "BASIC_DICTIONARY"
  // 字典配置V2
  | "BASIC_DICTIONARYV2"
  // 客户管理（医院）/我的客户
  | "CUSTOMER_MANGE_HOSPITAL_MY_CUSTOMER"
  // 交易管理
  | "TRANSACTIONDATA_TRANSACTIONMANAGE"
  // 小红书-聚光/线索列表
  | "XHSSPOTLIGHT_THREADLIST"
  // 小红书-聚光/小红书广告主
  | "XHSSPOTLIGHT_ADVERTISE"
  // 广告投放管理/小红书投放
  | "ADPUTMANAGE_XHSADPUT"
  // 个人业绩明细
  | "REPORT_FORMS_MANAGE_PERSONAL"
  // 员工明细
  | "EMPLOYEE_DETAILS"
  // 团队业绩总览
  | "TEAM_PERFORMANCE_OVERVIEW"
  // 团队业绩总览-明细
  | "TEAM_PERFORMANCE_OVERVIEW_DETAIL"
  // 报表管理-主播数据
  | "REPORTFORMS_MANAGE_LIVE_DATA"
  // 报表管理-下载中心
  | "DOWNLOAD"
  // 报表管理-咨询师接单数量
  | "CONSULT_ORDER"
  // 报表管理-团队业绩明细
  | "TEAM_PERFORMANCE_DETAIL"
  // 报表管理-团队业绩总览-渠道详情
  | "REPORTFORMSMANAGE_TEAM_DETAIL"
  // 客户抽屉-派单记录
  | "MY_CUSTOMER_ORDER_DISPATCH_RECORD"
  // 客户抽屉-成交记录
  | "MY_CUSTOMER_TRANSACTION_RECORD"
  // 客户抽屉-跟进记录
  | "MY_CUSTOMER_FOLLOW_UP_RECORD"
  // 客户抽屉-到院记录
  | "MY_CUSTOMER_VISIT_RECORD"
  // 客户抽屉-机构联系记录
  | "MY_CUSTOMER_ORGANIZATION_RECORD"
  // 不能为空
  | ""
  // 工作计划-任务总览-任务清单
  | "TASKLIST_LIST_TABLE"
  // 查重弹窗table
  | "REPEAT_TABLE"
  //今日任务-今日截止待完成
  | "TODAY_DEADLINE_UNFINISHED"
  //今日任务-今日总待完成
  | "TODAY_TOTAL_UNFINISHED"
  // 任务看板-今日数据-咨询师数据列表
  | "LIST_OF_CONSULTANTS_LIST_TABLE"
  //  任务看板-今日数据-咨询师-日期数据列表
  | "LIST_OF_CONSULTANTS_LIST_TABLE_BY_DATE"
  //  任务看板-今日数据-部门数据列表
  | "LIST_OF_CONSULTANTS_LIST_DPT_TABLE"
  //  任务看板-今日数据-部门-日期数据列表
  | "LIST_OF_CONSULTANTS_LIST_DPT_TABLE_BY_DATE"
  // 任务看板-往日数据-咨询师数据列表
  | "PAST_LIST_OF_CONSULTANTS_LIST_TABLE"
  //  任务看板-往日数据-咨询师-日期数据列表
  | "PAST_LIST_OF_CONSULTANTS_LIST_TABLE_BY_DATE"
  //  任务看板-往日数据-部门数据列表
  | "PAST_LIST_OF_CONSULTANTS_LIST_DPT_TABLE"
  //  任务看板-往日数据-部门-日期数据列表
  | "PAST_LIST_OF_CONSULTANTS_LIST_DPT_TABLE_BY_DATE"
  // 任务策略-我执行的策略
  | "MY_EXCUTE_STARTEGY"
  // 任务策略-我管理的策略
  | "MY_MANAGE_STARTEGY"
  // 任务策略-我管理的策略-任务配置
  | "MY_MANAGE_STARTEGY_TASK_SETTING"
  // 广告计划管理表格
  | "ADVERTISING_PLAN_MANAGEMENT_LIST_TABLE"
  //报表管理-主播数据-Drawer-主播数据详情
  | "REPORT_MANAGE_LIVE_DATA_DETAILS"
  // 报表管理-主播数据-Drawer-客户明细
  | "REPORT_MANAGE_LIVE_DATA_CUSTOMER_DETAILS"
  // 报表管理-主播数据-Drawer-成交明细
  | "REPORT_MANAGE_LIVE_DATA_DEAL_DETAILS";
