import {
  AdvertisingPlanManagement,
  BasicConfig,
  Channel,
  ConsultOrder,
  Cust,
  CustLeads,
  DealRecordIcon,
  DeptIcon,
  Dictionary,
  DownLoadCenterExcel,
  Employee,
  HospitalCust,
  HostsIcon,
  MainDataIcon,
  Org,
  PermissionIcon,
  PersonalReportExcel,
  PlatformIcon,
  ProjectIcon,
  ReportCenterExcel,
  ReportExcel,
  RoleIcon,
  Scheduler,
  TaskBoard,
  TaskOverview,
  TaskStrategy,
  TeamReportExcel,
  ToadyTask,
  UserBind,
  WorkPlan,
  XhsScheduler,
} from "@/router/svg";
import { lazy } from "react";

export const routerList = [
  {
    key: "/welcome",
    element: lazy(() => import("@/pages/welcome/index")),
    title: "",
    auth: "",
  },
  {
    key: "/noPermission",
    element: lazy(() => import("@/components/TXNoPermission")),
    title: "",
    auth: "",
  },
  {
    icon: <WorkPlan />,
    key: "/workplan",
    title: "工作计划",
    auth: "workPlan",
    children: [
      {
        key: "/workplan/toadyTask",
        element: lazy(() => import("@/pages/WorkPlan/TodayTask")),
        auth: "todayTask",
        title: "今日任务",
        icon: <ToadyTask />,
      },
      {
        key: "/workplan/taskOverview",
        element: lazy(() => import("@/pages/WorkPlan/TaskOverview")),
        auth: "taskOverview",
        title: "任务总览",
        icon: <TaskOverview />,
      },
      {
        key: "/workplan/taskBoard",
        element: lazy(() => import("@/pages/WorkPlan/TaskBoard")),
        auth: "taskBoard",
        title: "任务看板",
        icon: <TaskBoard />,
      },
      {
        key: "/workplan/taskStrategy",
        element: lazy(() => import("@/pages/WorkPlan/TaskStrategy")),
        auth: "taskStrategy",
        title: "任务策略",
        icon: <TaskStrategy />,
      },
    ],
  },
  {
    key: "/customerAssign",
    auth: "customerAssign",
    title: "客户指派",
    icon: <CustLeads />,
    children: [
      {
        key: "/customerAssign/assginList",
        element: lazy(() => import("@/pages/CustomerAssign")),
        auth: "customerAssignTask",
        title: "我的指派任务",
        icon: <CustLeads />,
      },
    ],
  },
  {
    key: "/customerManage",
    auth: "customerManagement",
    title: "客户管理",
    icon: <Cust />,
    children: [
      {
        key: "/customerManage/myCustomer",
        element: lazy(() => import("@/pages/customerManage/MyCustomerV2")),
        auth: "customer",
        title: "我的客户",
        icon: <Cust />,
      },
    ],
  },
  {
    key: "/orgManage",
    auth: "organizationManagement",
    title: "机构管理",
    icon: <Org />,
    children: [
      {
        key: "/orgManage/OrgManagement",
        element: lazy(() => import("@/pages/orgManage/OrgManagement")),
        auth: "organization",
        title: "机构管理",
        icon: <Org />,
      },

      {
        key: "/orgManage/employeeBind",
        element: lazy(() => import("@/pages/orgManage/EmployeeBindV2")),
        auth: "userOrgRelation",
        title: "员工机构绑定",
        icon: <UserBind />,
      },
    ],
  },
  {
    key: "/workforce",
    auth: "schedulingManagement",
    title: "排班管理",
    icon: <Scheduler />,
    children: [
      {
        key: "/workforce/xhsWorkforce",
        element: lazy(() => import("@/pages/workforce/XhsWorkforceV2")),
        auth: "redBookScheduling",
        title: "小红书排班",
        icon: <XhsScheduler />,
      },
      {
        key: "/workforce/channelGrouping",
        element: lazy(
          () => import("@/pages/SchedulingManagement/ChannelGrouping")
        ),
        auth: "redBookChannelGroup",
        title: "小红书渠道分组",
        icon: <XhsScheduler />,
      },
    ],
  },
  {
    key: "/channel",
    auth: "channelManagement",
    title: "渠道管理",
    icon: <Channel />,
    children: [
      {
        key: "/channel/channelManage",
        element: lazy(() => import("@/pages/channel/ChannelMangement")),
        auth: "channel",
        title: "渠道管理",
        icon: <Channel />,
      },
      {
        key: "/channel/employeeBind",
        element: lazy(() => import("@/pages/channel/EmployeeBindV2")),
        auth: "userChannelRelation",
        title: "员工渠道绑定",
        icon: <UserBind />,
      },
      {
        key: "/channel/advertisingPlanManagement",
        element: lazy(() => import("@/pages/AdvertisingPlanManagement")),
        // auth: "",
        auth: "campaign",
        title: "广告计划管理",
        icon: <AdvertisingPlanManagement />,
      },
    ],
  },
  {
    key: "/mainData",
    auth: "masterDataManagement",
    title: "主数据管理",
    icon: <MainDataIcon />,
    children: [
      {
        key: "/mainData/anchorManage",
        element: lazy(() => import("@/pages/mainData/AnchorManageV2")),
        auth: "liveStreamer",
        title: "主播管理",
        icon: <HostsIcon />,
      },
      {
        key: "/mainData/platformManage",
        element: lazy(() => import("@/pages/mainData/PlatformManageV2")),
        auth: "platform",
        title: "平台管理",
        icon: <PlatformIcon />,
      },

      {
        key: "/mainData/projectManage",
        element: lazy(() => import("@/pages/mainData/ProjectManagment")),
        auth: "project",
        title: "医美项目管理",
        icon: <ProjectIcon />,
      },
    ],
  },
  {
    icon: <BasicConfig />,
    key: "/basic",
    auth: "bacisManagement",
    title: "基础配置",
    children: [
      {
        auth: "role",
        key: "/basic/role",
        element: lazy(() => import("@/pages/basic/RoleV2")),
        title: "角色配置",
        icon: <RoleIcon />,
      },
      {
        auth: "dept",
        key: "/basic/department",
        element: lazy(() => import("@/pages/basic/DepartmentV2")),
        title: "部门配置",
        icon: <DeptIcon />,
      },
      {
        auth: "user",
        icon: <Employee />,
        key: "/basic/Employee",
        element: lazy(() => import("@/pages/basic/EmployeeV2")),
        title: "员工管理",
      },
      {
        auth: "dict",
        icon: <Dictionary />,
        key: "/basic/dictionary",
        element: lazy(() => import("@/pages/basic/DictionaryV2")),
        title: "字典配置",
      },
      {
        auth: "menu",
        icon: <PermissionIcon />,
        key: "/basic/permission",
        element: lazy(() => import("@/pages/basic/PermissionV2")),
        title: "权限管理",
      },
    ],
  },
  {
    key: "/customerMangeHospital",
    auth: "customerMgmtInstitution",
    title: "客户管理（医院）",
    icon: <HospitalCust />,
    children: [
      {
        key: "/customerMangeHospital/myCustomer",
        element: lazy(() => import("@/pages/HospitalMyCustomer")),
        auth: "institutionalCustomer",
        title: "我的客户",
        icon: <HospitalCust />,
      },
    ],
  },
  {
    key: "/transactionData",
    auth: "customerDealData",
    title: "客户交易数据",
    icon: <DealRecordIcon />,
    children: [
      {
        key: "/transactionData/transactionManage",
        element: lazy(
          () => import("@/pages/transactionData/TransactionManageV2")
        ),
        auth: "dealManagement",
        title: "交易管理",
        icon: <DealRecordIcon />,
      },
    ],
  },
  {
    key: "/xhsSpotlight",
    auth: "littleRedBookAd",
    title: "小红书-聚光",
    icon: <XhsScheduler />,
    children: [
      {
        key: "/xhsSpotlight/threadList",
        element: lazy(() => import("@/pages/xhs-spotlight/ThreadListV2")),
        auth: "littleRedBookLeads",
        title: "线索列表",
        icon: <XhsScheduler />,
      },
      {
        key: "/xhsSpotlight/advertise",
        element: lazy(() => import("@/pages/xhs-spotlight/advertise")),
        auth: "advertiserManagement",
        title: "小红书广告主",
        icon: <XhsScheduler />,
      },
    ],
  },
  {
    key: "/reportFormsManage",
    auth: "report",
    title: "报表管理",
    icon: <ReportExcel />,
    children: [
      {
        key: "/reportFormsManage/personal",
        element: lazy(() => import("@/pages/reportFormsManage/personal")),
        auth: "personalPerformance",
        title: "个人业绩",
        icon: <PersonalReportExcel />,
      },
      {
        key: "/reportFormsManage/team",
        element: lazy(() => import("@/pages/reportFormsManage/team")),
        auth: "teamPerformanceView",
        title: "团队业绩",
        icon: <TeamReportExcel />,
      },
      {
        key: "/reportFormsManage/reportForms",
        element: lazy(() => import("@/pages/reportFormsManage/reportForms")),
        auth: "reportCenter",
        title: "报表中心",
        icon: <ReportCenterExcel />,
      },
      {
        key: "/reportFormsManage/LiveData",
        element: lazy(() => import("@/pages/reportFormsManage/LiveDataV2")),
        auth: "anchorTransactionDataReport",
        title: "主播数据",
        icon: <ReportCenterExcel />,
      },
      {
        key: "/reportFormsManage/download",
        element: lazy(() => import("@/pages/reportFormsManage/download")),
        auth: "downloadCenter",
        title: "下载中心",
        icon: <DownLoadCenterExcel />,
      },
      {
        key: "/consultOrder",
        auth: "consultantsCustomerCount",
        title: "咨询师接单数量",
        element: lazy(() => import("@/pages/Report/ConsultOrder")),
        icon: <ConsultOrder />,
      },
    ],
  },
];
